development:
  facebook_app_id: 468035339997204
  facebook_key: "9fd33e885dbc43b87e7ad50448c1f68a"
  twitter_api_key: "N3NQYWgErSJRsUkt9MoCPtfQh"
  twitter_key: "N3NQYWgErSJRsUkt9MoCPtfQh"
  twitter_secret: "V0fbSA8wt5Tv1kjtU33vyyWCfKpDWL4EYwHHLAmtfPzdovUlWq"